try{
    const a = 0
    const b =17/0
    console.log(b)
} catch(weirdErr){
    console.log(weirdErr)
}

//read more